apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-migration-data
  namespace: studojo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: azurefile  # Use Azure File storage

