apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studojo-main-tls
  namespace: studojo
spec:
  secretName: studojo-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - studojo.com
    - www.studojo.com
    - api.studojo.com
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-studojo-com-tls
  namespace: studojo
spec:
  secretName: admin-studojo-com-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - admin.studojo.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: maverick-studojo-com-tls
  namespace: studojo
spec:
  secretName: maverick-studojo-com-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - maverick.studojo.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: partners-studojo-com-tls
  namespace: studojo
spec:
  secretName: partners-studojo-com-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - partners.studojo.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-studojo-com-tls
  namespace: studojo
spec:
  secretName: dev-studojo-com-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - dev.studojo.com

