apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-plane-k8s-access
  namespace: studojo
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

