import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("auth", "routes/auth.tsx"),
  route("auth/2fa", "routes/auth.2fa.tsx"),
  route("api/auth/share-token", "routes/api.auth.share-token.tsx"),
  route("api/auth/share-token-redirect", "routes/api.auth.share-token-redirect.tsx"),
  route("api/auth/*", "routes/api.auth.$.tsx"),
  route("api/onboarding/status", "routes/api.onboarding.status.tsx"),
  route("api/onboarding", "routes/api.onboarding.tsx"),
  route("api/resumes/parse", "routes/api.resumes.parse.tsx"),
  route("api/resumes/:id", "routes/api.resumes.$id.tsx"),
  route("api/resumes", "routes/api.resumes.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("settings", "routes/settings.tsx"),
  route("resumes", "routes/resumes.tsx"),
  route("assignments", "routes/assignments.tsx"),
  route("dojos/assignment", "routes/dojos.assignment.tsx"),
  route("dojos/careers", "routes/dojos.careers.tsx"),
  route("careers", "routes/careers.tsx"),
  route("api/careers/apply", "routes/api.careers.apply.tsx"),
  route("dissertation", "routes/dissertation.tsx"),
  route("api/dissertation", "routes/api.dissertation.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("refund-policy", "routes/refund-policy.tsx"),
  route("blog/:slug", "routes/blog.$slug.tsx"),
  route("blog", "routes/blog.tsx"),
  route("api/blog/:slug", "routes/api.blog.$slug.tsx"),
  route("api/blog", "routes/api.blog.tsx"),
  route("api/images/*", "routes/api.images.$.tsx"),
  route(".well-known/*", "routes/well-known.$.tsx"),
] satisfies RouteConfig;
